program putin_huilo;
	uses crt;
	var huilo:string;
	        i:integer;
	const xmax=80;
	begin
		textbackground(blue);
		textcolor(green);
		Clrscr;
		window(1,1,80,25);
		writeln('Кто хуйло?');
		read(huilo);
		gotoXY(40,2);
		textcolor(7);
		writeln(huilo,' ','хуйло');
		for i:=1 to xmax do write('-');
		textcolor(yellow);
		gotoXY(4,5);
		writeln(huilo,' ','хуйло!');
		delay(1000);
		gotoXY(15,6);
		textcolor(LightGreen);
		writeln('Ла-ла-ла-ла-ла-ла-ла-ла!');
		delay(1000);
		gotoXY(25,7);
		textcolor(LightRed);
		writeln('Ла-ла-ла-ла-ла-ла-ла-ла!');
		delay(1000);
		gotoXY(70,9);
		textcolor(white);
		writeln(huilo);
		delay(1000);
		gotoXY(5,10);
		textcolor(LightGreen);
		writeln('хуйло!');
		delay(1000);
		
		gotoXY(40,13);
		textcolor(magenta);
		writeln('Ла-');
		delay(300);
		textcolor(LightGreen);
		gotoXY(43,13);
		write('ла-');
		textcolor(LightMagenta);
		delay(300);
		gotoXY(48,13);
		textcolor(LightRed);
		write('ла-');
		delay(300);
		gotoXY(53,13);
		textcolor(Brown);
		write('ла-');
		delay(300);
		gotoXY(58,13);
		textcolor(LightMagenta);
		write('ла-');
		delay(300);
		gotoXY(63,13);
		textcolor(LightGreen);
		write('ла-');
		delay(300);
		gotoXY(68,13);
		textcolor(LightRed);
		write('ла-');
		delay(300);
		gotoXY(73,13);
		textcolor(LightGreen);
		write('ла!');
		delay(1000);
		
		gotoXY(30,14);
		textcolor(128);
		writeln('Ла-');
		delay(300);
		gotoXY(33,14);
		write('ла-');
		delay(300);
		gotoXY(38,14);
		write('ла-');
		delay(300);
		gotoXY(43,14);
		write('ла-');
		delay(300);
		gotoXY(48,14);
		write('ла-');
		delay(300);
		gotoXY(53,14);
		write('ла-');
		delay(300);
		gotoXY(58,14);
		write('ла-');
		delay(300);
		gotoXY(63,14);
		write('ла!');
		delay(1000);
		textcolor(yellow);
		gotoXY(1,25);
	end.
